<?php

namespace ContainerLVN8wUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WvyHe2FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WvyHe2F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WvyHe2F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'teacherRepository' => ['privates', 'App\\Repository\\TeacherRepository', 'getTeacherRepositoryService', true],
        ], [
            'teacherRepository' => 'App\\Repository\\TeacherRepository',
        ]);
    }
}
