<?php

namespace ContainerLVN8wUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3NHdr9wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3NHdr9w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3NHdr9w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ressource' => ['privates', '.errored..service_locator.3NHdr9w.App\\Entity\\Ressources', NULL, 'Cannot autowire service ".service_locator.3NHdr9w": it references class "App\\Entity\\Ressources" but no such service exists.'],
        ], [
            'ressource' => 'App\\Entity\\Ressources',
        ]);
    }
}
