<?php

namespace ContainerLVN8wUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1FDzbxN.App\Entity\Matter' shared service.
     *
     * @return \App\Entity\Matter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1FDzbxN": it references class "App\\Entity\\Matter" but no such service exists.');
    }
}
