<?php

namespace ContainerLVN8wUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatterTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MatterType' shared autowired service.
     *
     * @return \App\Form\MatterType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\MatterType.php';

        return $container->privates['App\\Form\\MatterType'] = new \App\Form\MatterType();
    }
}
