<?php

namespace ContainerLVN8wUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRessourcesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3NHdr9w.App\Entity\Ressources' shared service.
     *
     * @return \App\Entity\Ressources
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3NHdr9w": it references class "App\\Entity\\Ressources" but no such service exists.');
    }
}
