<?php

namespace ContainerQNYo1Tr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PEtc7uqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pEtc7uq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pEtc7uq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'levelRepository' => ['privates', 'App\\Repository\\LevelRepository', 'getLevelRepositoryService', true],
        ], [
            'levelRepository' => 'App\\Repository\\LevelRepository',
        ]);
    }
}
