<?php

namespace ContainerQNYo1Tr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dt_KdXxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dt.KdXx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dt.KdXx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LearnerController::delete' => ['privates', '.service_locator.HDk5VeF', 'get_ServiceLocator_HDk5VeFService', true],
            'App\\Controller\\LearnerController::edit' => ['privates', '.service_locator.HDk5VeF', 'get_ServiceLocator_HDk5VeFService', true],
            'App\\Controller\\LearnerController::index' => ['privates', '.service_locator.1xisnfh', 'get_ServiceLocator_1xisnfhService', true],
            'App\\Controller\\LearnerController::show' => ['privates', '.service_locator.HDk5VeF', 'get_ServiceLocator_HDk5VeFService', true],
            'App\\Controller\\LevelController::delete' => ['privates', '.service_locator.Xf66BK5', 'get_ServiceLocator_Xf66BK5Service', true],
            'App\\Controller\\LevelController::edit' => ['privates', '.service_locator.Xf66BK5', 'get_ServiceLocator_Xf66BK5Service', true],
            'App\\Controller\\LevelController::index' => ['privates', '.service_locator.pEtc7uq', 'get_ServiceLocator_PEtc7uqService', true],
            'App\\Controller\\LevelController::show' => ['privates', '.service_locator.Xf66BK5', 'get_ServiceLocator_Xf66BK5Service', true],
            'App\\Controller\\TeacherController::delete' => ['privates', '.service_locator.6P8ix8o', 'get_ServiceLocator_6P8ix8oService', true],
            'App\\Controller\\TeacherController::edit' => ['privates', '.service_locator.6P8ix8o', 'get_ServiceLocator_6P8ix8oService', true],
            'App\\Controller\\TeacherController::index' => ['privates', '.service_locator.WvyHe2F', 'get_ServiceLocator_WvyHe2FService', true],
            'App\\Controller\\TeacherController::show' => ['privates', '.service_locator.6P8ix8o', 'get_ServiceLocator_6P8ix8oService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\LearnerController:delete' => ['privates', '.service_locator.HDk5VeF', 'get_ServiceLocator_HDk5VeFService', true],
            'App\\Controller\\LearnerController:edit' => ['privates', '.service_locator.HDk5VeF', 'get_ServiceLocator_HDk5VeFService', true],
            'App\\Controller\\LearnerController:index' => ['privates', '.service_locator.1xisnfh', 'get_ServiceLocator_1xisnfhService', true],
            'App\\Controller\\LearnerController:show' => ['privates', '.service_locator.HDk5VeF', 'get_ServiceLocator_HDk5VeFService', true],
            'App\\Controller\\LevelController:delete' => ['privates', '.service_locator.Xf66BK5', 'get_ServiceLocator_Xf66BK5Service', true],
            'App\\Controller\\LevelController:edit' => ['privates', '.service_locator.Xf66BK5', 'get_ServiceLocator_Xf66BK5Service', true],
            'App\\Controller\\LevelController:index' => ['privates', '.service_locator.pEtc7uq', 'get_ServiceLocator_PEtc7uqService', true],
            'App\\Controller\\LevelController:show' => ['privates', '.service_locator.Xf66BK5', 'get_ServiceLocator_Xf66BK5Service', true],
            'App\\Controller\\TeacherController:delete' => ['privates', '.service_locator.6P8ix8o', 'get_ServiceLocator_6P8ix8oService', true],
            'App\\Controller\\TeacherController:edit' => ['privates', '.service_locator.6P8ix8o', 'get_ServiceLocator_6P8ix8oService', true],
            'App\\Controller\\TeacherController:index' => ['privates', '.service_locator.WvyHe2F', 'get_ServiceLocator_WvyHe2FService', true],
            'App\\Controller\\TeacherController:show' => ['privates', '.service_locator.6P8ix8o', 'get_ServiceLocator_6P8ix8oService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\LearnerController::delete' => '?',
            'App\\Controller\\LearnerController::edit' => '?',
            'App\\Controller\\LearnerController::index' => '?',
            'App\\Controller\\LearnerController::show' => '?',
            'App\\Controller\\LevelController::delete' => '?',
            'App\\Controller\\LevelController::edit' => '?',
            'App\\Controller\\LevelController::index' => '?',
            'App\\Controller\\LevelController::show' => '?',
            'App\\Controller\\TeacherController::delete' => '?',
            'App\\Controller\\TeacherController::edit' => '?',
            'App\\Controller\\TeacherController::index' => '?',
            'App\\Controller\\TeacherController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\LearnerController:delete' => '?',
            'App\\Controller\\LearnerController:edit' => '?',
            'App\\Controller\\LearnerController:index' => '?',
            'App\\Controller\\LearnerController:show' => '?',
            'App\\Controller\\LevelController:delete' => '?',
            'App\\Controller\\LevelController:edit' => '?',
            'App\\Controller\\LevelController:index' => '?',
            'App\\Controller\\LevelController:show' => '?',
            'App\\Controller\\TeacherController:delete' => '?',
            'App\\Controller\\TeacherController:edit' => '?',
            'App\\Controller\\TeacherController:index' => '?',
            'App\\Controller\\TeacherController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
