<?php

namespace ContainerJBoO1U5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HDk5VeFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HDk5VeF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HDk5VeF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'learner' => ['privates', '.errored..service_locator.HDk5VeF.App\\Entity\\Learner', NULL, 'Cannot autowire service ".service_locator.HDk5VeF": it references class "App\\Entity\\Learner" but no such service exists.'],
        ], [
            'learner' => 'App\\Entity\\Learner',
        ]);
    }
}
