<?php

namespace ContainerUnYWQil;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLearnerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HDk5VeF.App\Entity\Learner' shared service.
     *
     * @return \App\Entity\Learner
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HDk5VeF": it references class "App\\Entity\\Learner" but no such service exists.');
    }
}
