<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxgCgQW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxgCgQW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxgCgQW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxgCgQW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxgCgQW\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxgCgQW',
    'container.build_id' => '25b1899a',
    'container.build_time' => 1594560974,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxgCgQW');
