<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJBoO1U5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJBoO1U5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJBoO1U5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJBoO1U5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJBoO1U5\App_KernelDevDebugContainer([
    'container.build_hash' => 'JBoO1U5',
    'container.build_id' => '3fd206f2',
    'container.build_time' => 1594499694,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJBoO1U5');
