<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'learner_index' => [[], ['_controller' => 'App\\Controller\\LearnerController::index'], [], [['text', '/learner/']], [], []],
    'learner_new' => [[], ['_controller' => 'App\\Controller\\LearnerController::new'], [], [['text', '/learner/new']], [], []],
    'learner_show' => [['id'], ['_controller' => 'App\\Controller\\LearnerController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/learner/show']], [], []],
    'learner_edit' => [['id'], ['_controller' => 'App\\Controller\\LearnerController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/learner/edit']], [], []],
    'learner_delete' => [['id'], ['_controller' => 'App\\Controller\\LearnerController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/learner/delete']], [], []],
    'level_index' => [[], ['_controller' => 'App\\Controller\\LevelController::index'], [], [['text', '/level/']], [], []],
    'level_new' => [[], ['_controller' => 'App\\Controller\\LevelController::new'], [], [['text', '/level/new']], [], []],
    'level_show' => [['id'], ['_controller' => 'App\\Controller\\LevelController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/level']], [], []],
    'level_edit' => [['id'], ['_controller' => 'App\\Controller\\LevelController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/level']], [], []],
    'level_delete' => [['id'], ['_controller' => 'App\\Controller\\LevelController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/level']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\PagesController::home'], [], [['text', '/']], [], []],
    'teacher_index' => [[], ['_controller' => 'App\\Controller\\TeacherController::index'], [], [['text', '/teacher/']], [], []],
    'teacher_new' => [[], ['_controller' => 'App\\Controller\\TeacherController::new'], [], [['text', '/teacher/new']], [], []],
    'teacher_show' => [['id'], ['_controller' => 'App\\Controller\\TeacherController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teacher/show']], [], []],
    'teacher_edit' => [['id'], ['_controller' => 'App\\Controller\\TeacherController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teacher/edit']], [], []],
    'teacher_delete' => [['id'], ['_controller' => 'App\\Controller\\TeacherController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teacher/delete']], [], []],
];
